secrets:
  # These secrets are used by Authelia
  JWT_SECRET:
    file: ${SECRETS_DIR}/JWT_SECRET
  SESSION_SECRET:
    file: ${SECRETS_DIR}/SESSION_SECRET
  STORAGE_ENCRYPTION_KEY:
    file: ${SECRETS_DIR}/STORAGE_ENCRYPTION_KEY
  # These secrets are for using Authelia as an OIDC provider
  HMAC_SECRET:
    file: ${SECRETS_DIR}/HMAC_SECRET
  JWT_PRIVATE_KEY:
    file: ${SECRETS_DIR}/certs/private.pem
  DEX_CLIENT_SECRET_DIGEST:
    file: ${SECRETS_DIR}/DEX_CLIENT_SECRET_DIGEST

services:
  traefik:
    container_name: traefik
    image: traefik:latest
    ports:
      # HTTP Ports
      - "80:80"
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
      - "8082:8082"
    command:
      - '--providers.file.filename=/settings/traefik.yaml'
      - '--entryPoints.web.address=:80'
    volumes:
      - ./config/traefik.yaml:/settings/traefik.yaml
      - ./config/secrets/acme_certificates:/acme

  grist:
    container_name: grist
    image: gristlabs/grist:latest
    ports:
      - 8484:8484
    environment:
      APP_HOME_URL: ${APP_HOME_URL}

      #GRIST_OIDC_SP_HOST: https://${DEX_DOMAIN}
      GRIST_OIDC_IDP_ISSUER: http://dex:5556/dex
      GRIST_OIDC_IDP_CLIENT_ID: ${GRIST_OIDC_IDP_CLIENT_ID}
      GRIST_OIDC_IDP_CLIENT_SECRET: ${GRIST_OIDC_IDP_CLIENT_SECRET}
      GRIST_OIDC_IDP_END_SESSION_ENDPOINT: ${APP_HOME_URL}/signed-out

      # Working with multiple teams is possible but a little harder to
      # explain and understand, and the UI has rough edges.
      GRIST_SINGLE_ORG: ${TEAM}
      # Force users to login (disable anonymous access)
      GRIST_FORCE_LOGIN: false
      # Default email for the "Admin" account
      GRIST_DEFAULT_EMAIL: ${DEFAULT_EMAIL:-test@example.org}
    restart: always
    volumes:
      # Where to store persistent data, such as documents.
      - ${PERSIST_DIR}/grist:/persist
    depends_on:
      traefik:
        condition: service_started
      dex:
        condition: service_started
  
  dex:
    restart: always
    container_name: dex
    image: dexidp/dex:latest
    volumes:
      - ./config/dex.yaml:/etc/dex/config.docker.yaml
      - ./${PERSIST_DIR}/auth/:/persist/auth
    ports:
      - 5556:5556
    environment:
      APP_HOME_URL: ${APP_HOME_URL}
      GRIST_OIDC_IDP_CLIENT_ID: ${GRIST_OIDC_IDP_CLIENT_ID}
      GRIST_OIDC_IDP_CLIENT_SECRET: ${GRIST_OIDC_IDP_CLIENT_SECRET}
      DEX_CLIENT_SECRET_DIGEST: ${DEX_CLIENT_SECRET_DIGEST}
      DEX_DOMAIN: ${DEX_DOMAIN}
    depends_on:
      authelia:
        condition: service_healthy

  authelia:
    container_name: authelia
    image: authelia/authelia:4
    secrets:
      - HMAC_SECRET
      - JWT_SECRET
      - JWT_PRIVATE_KEY
      - DEX_CLIENT_SECRET_DIGEST
      - SESSION_SECRET
      - STORAGE_ENCRYPTION_KEY
    environment:
      AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE: '/run/secrets/JWT_SECRET'
      AUTHELIA_SESSION_SECRET_FILE: '/run/secrets/SESSION_SECRET'
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: '/run/secrets/STORAGE_ENCRYPTION_KEY'
      HMAC_SECRET_FILE: '/run/secrets/HMAC_SECRET'
      JWT_PRIVATE_KEY_FILE: '/run/secrets/JWT_PRIVATE_KEY'
      # Domain Dex is hosted at. Custom variable that's interpolated into the Authelia config
      APP_DOMAIN: 127.0.0.1
      # Where Authelia should redirect to after successful authentication.
      DEX_OAUTH_CALLBACK_URL: 'https://${DEX_DOMAIN}/oauth2/callback'
      # Hash of the client secret provided to Dex.
      DEX_CLIENT_SECRET_DIGEST_FILE: "/run/secrets/DEX_CLIENT_SECRET_DIGEST"
    volumes:
      - ./config/authelia:/config
      - ${PERSIST_DIR}/authelia:/persist
    command:
      - 'authelia'
      - '--config=/config/configuration.yml'
      # Enables templating in the config file
      - '--config.experimental.filters=template'
