secrets:
  # These secrets are used by Authelia
  JWT_SECRET:
    file: ${SECRETS_DIR}/JWT_SECRET
  SESSION_SECRET:
    file: ${SECRETS_DIR}/SESSION_SECRET
  STORAGE_ENCRYPTION_KEY:
    file: ${SECRETS_DIR}/STORAGE_ENCRYPTION_KEY
  # These secrets are for using Authelia as an OIDC provider
  HMAC_SECRET:
    file: ${SECRETS_DIR}/HMAC_SECRET
  JWT_PRIVATE_KEY:
    file: ${SECRETS_DIR}/certs/private.pem
  DEX_CLIENT_SECRET_DIGEST:
    file: ${SECRETS_DIR}/DEX_CLIENT_SECRET_DIGEST

services:
  grist:
    image: gristlabs/grist:latest
    environment:
      # Base URL Grist redirects to when navigating. Change this to your domain.
      APP_HOME_URL: ${APP_HOME_URL}

      GRIST_OIDC_SP_HOST: ${APP_HOME_URL}
      GRIST_OIDC_IDP_ISSUER: http://${DEX_DOMAIN}
      GRIST_OIDC_IDP_CLIENT_ID: ${GRIST_OIDC_IDP_CLIENT_ID}
      GRIST_OIDC_IDP_CLIENT_SECRET: ${GRIST_OIDC_IDP_CLIENT_SECRET}
      GRIST_OIDC_IDP_END_SESSION_ENDPOINT: ${APP_HOME_URL}/signed-out

      # Working with multiple teams is possible but a little harder to
      # explain and understand, and the UI has rough edges.
      GRIST_SINGLE_ORG: ${TEAM}
      # Force users to login (disable anonymous access)
      GRIST_FORCE_LOGIN: true
      # Default email for the "Admin" account
      GRIST_DEFAULT_EMAIL: ${DEFAULT_EMAIL:-test@example.org}
    restart: always
    volumes:
      # Where to store persistent data, such as documents.
      - ${PERSIST_DIR}/grist:/persist
    labels:
      - "traefik.http.services.grist.loadbalancer.server.port=8484"
      - "traefik.http.routers.grist.rule=Host(`${GRIST_DOMAIN}`)"
      - "traefik.http.routers.grist.service=grist"
      # Uncomment and configure in traefik-config.yml to enable automatic HTTPS certificate setup.
      #- "traefik.http.routers.grist.tls.certresolver=letsencrypt"
    depends_on:
      # Grist attempts to setup OIDC when it starts, making a request to the OIDC service.
      # This will fail if Dex isn't ready and reachable.
      # Traefik will only start routing to Dex when it's registered as healthy.
      # Making Grist wait for Dex to be healthy should avoid this issue.
      dex:
        condition: service_healthy
      traefik:
        condition: service_started

  traefik:
    image: traefik:latest
    ports:
      # HTTP Ports
      - "80:80"
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
      - "8082:8082"
    volumes:
      # Set the config file for traefik - this is loaded automatically.
      - ./config/traefik/config.yml:/etc/traefik/traefik.yml
      # Certificate location, if automatic certificate setup is enabled.
      - ./config/secrets/acme_certificates:/acme
      # Traefik needs docker access when configured via docker labels.
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      default:
        aliases:
          # Enables Grist to resolve this domain to Traefik when doing OIDC setup.
          - ${DEX_DOMAIN}

  dex:
    restart: always
    container_name: dex
    image: dexidp/dex:latest
    volumes:
      - ./config/dex.yaml:/etc/dex/config.yaml
    ports:
      - 5556:5556
    environment:
      APP_HOME_URL: ${APP_HOME_URL}
      GRIST_OIDC_IDP_CLIENT_ID: ${GRIST_OIDC_IDP_CLIENT_ID}
      GRIST_OIDC_IDP_CLIENT_SECRET: ${GRIST_OIDC_IDP_CLIENT_SECRET}
    healthcheck:
      test: ["CMD", "wget", "-O", "/dev/null", "http://localhost:5556/healthz"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s

  authelia:
    image: authelia/authelia:4
    secrets:
      - HMAC_SECRET
      - JWT_SECRET
      - JWT_PRIVATE_KEY
      - DEX_CLIENT_SECRET_DIGEST
      - SESSION_SECRET
      - STORAGE_ENCRYPTION_KEY
    environment:
      AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE: '/run/secrets/JWT_SECRET'
      AUTHELIA_SESSION_SECRET_FILE: '/run/secrets/SESSION_SECRET'
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: '/run/secrets/STORAGE_ENCRYPTION_KEY'
      HMAC_SECRET_FILE: '/run/secrets/HMAC_SECRET'
      JWT_PRIVATE_KEY_FILE: '/run/secrets/JWT_PRIVATE_KEY'
      # Domain Dex is hosted at. Custom variable that's interpolated into the Authelia config
      APP_DOMAIN: ${DEX_DOMAIN}
      # Where Authelia should redirect to after successful authentication.
      DEX_OAUTH_CALLBACK_URL: https://${DEX_DOMAIN}/callback
      # Hash of the client secret provided to Dex.
      DEX_CLIENT_SECRET_DIGEST_FILE: "/run/secrets/DEX_CLIENT_SECRET_DIGEST"
    volumes:
      - ./config/authelia:/config
      - ${PERSIST_DIR}/authelia:/persist
    command:
      - 'authelia'
      - '--config=/config/configuration.yml'
      # Enables templating in the config file
      - '--config.experimental.filters=template'
    labels:
      - "traefik.http.services.authelia.loadbalancer.server.port=9091"
      - "traefik.http.routers.authelia.rule=Host(`${AUTHELIA_DOMAIN}`)"
      - "traefik.http.routers.authelia.service=authelia"
      # Uncomment and configure in traefik-config.yml to enable automatic HTTPS certificate setup.
      #- "traefik.http.routers.authelia.tls.certresolver=letsencrypt"
