#!/bin/bash

# Define the paths to the files
script_dir=$(dirname "$0")
localfile_path="$script_dir/rc.local"
restartgrist_path="$script_dir/restartGrist"
gristparameters_path="$script_dir/gristParameters"
dexyaml_path="$script_dir/dex.yaml"

instalation_path="~/grist"

# Check if the files exist
for file_path in "$localfile_path" "$restartgrist_path" "$gristparameters_path" "$dexyaml_path"; do
    if [ ! -f "$file_path" ]; then
        echo "File not found: $file_path"
        exit 1
    fi
done

# Add execute permissions to the files
for file_path in "$localfile_path" "$restartgrist_path" "$gristparameters_path"; do
    chmod +x "$file_path"
    if [ $? -ne 0 ]; then
        echo "Failed to change permissions for: $file_path"
        exit 1
    fi
done

# Check if ~/grist exists and create it if it doesn't
if [ ! -d $instalation_path ]; then
    mkdir $instalation_path
fi

# Initialize flags
force=0
rc=0
r=0
p=0
d=0

# Parse command-line options
# -f: force flag, if set, files will be moved even if they already exist at the destination
# -a: all flag, if set, all files will be moved
# -r: restartGrist flag, if set, the restartGrist file will be moved
# -p: gristParameters flag, if set, the gristParameters file will be moved
# -d: dex.yaml flag, if set, the dex.yaml file will be moved
# -rc: rc.local flag, if set, the rc.local file will be moved
while getopts "f:arpdrc" opt; do
    case $opt in
        f)
            force=1
            ;;
        a)
            rc=1
            r=1
            p=1
            d=1
            ;;
        r)
            r=1
            ;;
        p)
            p=1
            ;;
        d)
            d=1
            ;;
        rc)
            rc=1
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            exit 1
            ;;
    esac
done

# Move the files to their destinations
if [ $force -eq 1 -o ! -f "/etc/$(basename $localfile_path)" ] && [ $rc -eq 1 ]; then
    mv -f "$localfile_path" /etc
    echo "Moved: $localfile_path"
elif [ $rc -eq 1 ]; then
    echo "File already exists and was not moved: $localfile_path"
fi

if [ $force -eq 1 -o ! -f "$instalation_path/$(basename $restartgrist_path)" ] && [ $r -eq 1 ]; then
    mv -f "$restartgrist_path" $instalation_path
    echo "Moved: $restartgrist_path"
elif [ $r -eq 1 ]; then
    echo "File already exists and was not moved: $restartgrist_path"
fi

if [ $force -eq 1 -o ! -f "$instalation_path/$(basename $gristparameters_path)" ] && [ $p -eq 1 ]; then
    mv -f "$gristparameters_path" $instalation_path
    echo "Moved: $gristparameters_path"
elif [ $p -eq 1 ]; then
    echo "File already exists and was not moved: $gristparameters_path"
fi

if [ $force -eq 1 -o ! -f "$instalation_path/$(basename $dexyaml_path)" ] && [ $d -eq 1 ]; then
    mv -f "$dexyaml_path" $instalation_path
    echo "Moved: $dexyaml_path"
elif [ $d -eq 1 ]; then
    echo "File already exists and was not moved: $dexyaml_path"
fi