#!/bin/bash

set +o histexpand

yellow='\e[33m'
green='\e[32m'
cyan='\e[36m'
normal='\e[m'

printf "










	${yellow}Welcome to Grist Builder Edition"'!'"${normal}

	The Grist installation is under the ${green}grist${normal} user. Run

	    ${cyan}sudo -iu grist${normal}

	to manage the installation.
" > /etc/motd
